name: Test max free space
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: "Free Space"
    steps:
    - name: Checkout config
      uses: actions/checkout@v2

    - name: Host info
      run: |
        echo "Disk space:"
        df -h /
        sudo ls -alh /usr/local/lib
        sudo ls -alh /mnt

    - name: Free disk space
      run: |
        chmod +x ./free-space.sh
        ./free-space.sh
        sudo rm -rf /usr/share/dotnet

    - name: Host info
      run: |
        echo "Disk space:"
        df -h /
        sudo du -h -d 1 /usr

