name: Test max free space
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: "Free Space"
    steps:
    - name: Checkout config
      uses: actions/checkout@v2

    - name: Disk space
      run: |
        df -h /

    - name: Free disk space
      run: |
        chmod +x ./free-up-space.sh
        ./free-up-space.sh

    - name: Disk space
      run: |
        df -h /
